#colour thresholding

blue_threshold:
  min_threshold_1:
    - 56
    - 68
    - 93
  max_threshold_1:
    - 133
    - 206
    - 205

  min_threshold_2:
    - 84
    - 24
    - 126
  max_threshold_2:
    - 255
    - 129
    - 255


#this is red for testing
red_threshold:
  min_threshold_1:
    - 0
    - 0
    - 227
  max_threshold_1:
    - 206
    - 180
    - 255

  min_threshold_2:
    - 173
    - 166
    - 79
  max_threshold_2:
    - 255
    - 255
    - 255

min_area: 1100
