#colour thresholding

blue_threshold:
  min_threshold_1:
    - 28
    - 0
    - 165
  max_threshold_1:
    - 128
    - 123
    - 255

  min_threshold_2:
    - 84
    - 24
    - 126
  max_threshold_2:
    - 255
    - 129
    - 255


#this is red for testing
# blue_threshold:
#   min_threshold_1:
#     - 127
#     - 80
#     - 64
#   max_threshold_1:
#     - 179
#     - 217
#     - 124

#   min_threshold_2:
#     - 173
#     - 166
#     - 79
#   max_threshold_2:
#     - 255
#     - 255
#     - 255

min_area: 1500